/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public int sum(int x, int y) {
    return x + y;
  }

  public double average(int x, int y) {
    return (x + y) / 2;
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.print("Sum of 2 and 3 is " + new App().sum(2, 3) + ".Average is " + new App().average(2, 3) + ".");
  }
}
